Repository wecode-bootcamp-korea/38-2nd-KRWEAM-backend, pull requests merged in 2022-11, with the labels that each got.

#2 [38기 김택수] ADD : 환경세팅 완료
  .env.sample
  .gitignore
  controllers/testController.js
  krweam.js
  models/testDao.js
  package-lock.json
  package.json
  routers/index.js
  routers/testRouter.js
  services/testService.js
  util/dataSourceWrapperClass.js
  util/globalErrorHandler.js
Labels: 수정 요청

#3 [38기 김택수] ADD : DB Migration
  db/migrations/20221101064330_cerate_users_table.sql
  db/migrations/20221101064338_cerate_genders_table.sql
  db/migrations/20221101064344_cerate_brands_table.sql
  db/migrations/20221101064350_cerate_categories_table.sql
  db/migrations/20221101064356_cerate_products_table.sql
  db/migrations/20221101064402_cerate_sizes_table.sql
  db/migrations/20221101064410_cerate_buy_prices__table.sql
  db/migrations/20221101064420_cerate_sell_price_table.sql
  db/migrations/20221101064429_cerate_interested_items_table.sql
  db/migrations/20221101064441_cerate_deal_histories_table.sql
  krweam.js
  util/dataSourceWrapperClass.js
Labels: 멘토 리뷰 요청

#4 [38기 김택수] MODIFY : product table에 color column 추가
  db/migrations/20221102070016_modify_products_table.sql
Labels: 멘토 리뷰 요청

#6 [MODIFY] wrapperClass 수정
  krweam.js
  package-lock.json
  package.json
  util/dataSourceWrapperClass.js
Labels: 멘토 리뷰 요청

#5 [MODIFY] categories table에서 english_name column 삭제
  db/migrations/20221103051607_modify_categories_table.sql
Labels: 멘토 리뷰 요청

#7 [38기 김택수] 구매 및 판매입찰 / 즉시구매 / 포인트차감 및 추가 Transaction 구현
  controllers/dealController.js
  controllers/testController.js
  models/dealDao.js
  models/testDao.js
  routers/dealRouter.js
  routers/index.js
  routers/testRouter.js
  services/dealService.js
  services/testService.js
  util/dataSourceWrapperClass.js
  util/globalErrorHandler.js
Labels: 멘토 리뷰 요청

#8 [ADD] 소셜 로그인 및 회원가입/로그인 API 구현
  controllers/userController.js
  db/migrations/20221104075420_modify_users_table.sql
  models/enums.js
  models/userDao.js
  package-lock.json
  package.json
  routers/index.js
  routers/testRouter.js
  routers/userRouter.js
  services/userService.js
  util/auth.js
Labels: 멘토 리뷰 요청, 완료

#9 [38기 김택수] ADD : 마이페이지 구매내역 및 판매내역 조회 완료
  controllers/mypageController.js
  models/mypageDao.js
  routers/mypageRouter.js
  services/mypageService.js
Labels: 멘토 리뷰 요청

#10 [ADD] main 페이지에 필요한 상품 정보 전달 API 구현
  controllers/productController.js
  models/productDao.js
  routers/index.js
  routers/productRouter.js
  services/productService.js
Labels: 완료

#14 [38기 김택수] ADD : 구매 및 판매 로그인 middleware 적용
  controllers/dealController.js
  routers/dealRouter.js
  routers/index.js
  routers/testRouter.js
  util/auth.js
Labels: 멘토 리뷰 요청

#13 [38기 김택수] ADD : mypage endpoint 수정 및 bug fix
  controllers/mypageController.js
  routers/index.js
  routers/mypageRouter.js
  services/userService.js
Labels: 멘토 리뷰 요청

#11 [38기 김택수] ADD : 관심상품 추가/삭제 기능 및 조회 기능 구현
  controllers/wishController.js
  krweam.js
  models/wishDao.js
  package-lock.json
  package.json
  routers/index.js
  routers/wishRouter.js
  server.js
  services/wishService.js
Labels: 멘토 리뷰 요청

#15 [38기 김택수] ADD : 상세페이지 데이터 조회 완료
  controllers/productController.js
  models/productDao.js
  routers/productRouter.js
  services/productService.js
Labels: 멘토 리뷰 요청

#16 [38기 김택수] FIX : mypage 내 user정보 반환 기능 구현
  controllers/userController.js
  models/userDao.js
  routers/userRouter.js
  services/userService.js
Labels: 멘토 리뷰 요청

#17 [38기 김택수] ADD : 검색기능 구현
  controllers/searchController.js
  models/searchDao.js
  routers/index.js
  routers/searchRouter.js
  services/searchService.js
Labels: 멘토 리뷰 요청

#12 [ADD] list 페이지 sort 조건에 따른 product 배열 반환 API 구현
  controllers/productController.js
  models/productDao.js
  routers/index.js
  routers/productRouter.js
  services/productService.js
  services/userService.js
  util/auth.js
Labels: 완료

#18 [ADD] 유저 이메일, 비밀번호 변경하기 API 구현
  controllers/userController.js
  models/userDao.js
  routers/userRouter.js
  services/userService.js
Labels: 멘토 리뷰 요청, 완료

#19 [MODIFY] test 오류 수정
  controllers/productController.js
  controllers/wishController.js
  models/dealDao.js
  models/productDao.js
  routers/productRouter.js
  routers/userRouter.js
  services/productService.js
Labels: 멘토 리뷰 요청
